[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "MrovWeathers"
description = "New weather conditions, by mrov"
websiteUrl = "https://github.com/AndreyMrovol/LethalMrovWeathers"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
mrov-WeatherRegistry = "0.3.13"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../MrovWeathers/dist"

[[build.copy]]
source = "../MrovWeathers/bin/Release/netstandard2.1/MrovWeathers.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[[build.copy]]
source = "./bundles"
target = "/"

[publish]
communities = [ "lethal-company", ]